### ISSUE TITLE
Where is the definition of 'category'?

### ISSUE THREAD

**Issue by JacquesCarette** [semorrison/lean-category-theory#12]
I have looked everywhere in the files to find the definition of the record 'category', and I cannot find it. I am just interested in seeing how 'category' is defined in Lean at the moment.  

I was surprised to see that ``import categories.category`` doesn't mean that there has to be a **file** called `categories/category.lean` that corresponds to that.

**Comment by kim-em** [comment]
Somewhat confusingly, the actual definition of a category is in a separate
repository!

https://github.com/semorrison/lean-category-theory-pr/blob/master/src/categories/category.lean

In getting ready to PR material to mathlib, I made a whole separate
repository https://github.com/semorrison/lean-category-theory-pr/ which
contains just a small subset of what the whole library here, for a first
PR. That repository is now a dependency of this one.

**Comment by JacquesCarette** [comment]
Thank you.  Google found the current repository, but not the lean-category-pr one (and neither did I by poking around).

You might want to edit the README to make it clear this isn't a stand-alone repo?

**Comment by kim-em** [comment]
Thanks, I’ll definitely do that. I had intended the PR repository would be
a very short-lived one, but preparing the PR revealed some deep problems
with my handling of universes, which I’m only just now getting on top of
(during a period when I haven’t had much time for Lean). Hopefully it will
disappear again in not too long.
